config/routes.rb
YelpcampRails::Application.routes.draw do

    resources :campgrounds do
      resources :comments
    end

  root to: 'pages#landing'

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :street, :city, :state, :country, :zip_code

  validates :street, presence: true, length: { minimum: 3, maximum: 50 }
  validates :city, presence: true, length: { minimum: 3, maximum: 50 }
  validates :state, presence: true, length: { minimum: 3, maximum: 50 }
  validates :country, presence: true, length: { minimum: 3, maximum: 50 }
  validates :zip_code, presence: true, length: { minimum: 3, maximum: 50 }

  has_many :user, class_name: 'User'
  has_many :campground, class_name: 'Campground'
end

app/models/campground.rb
class Campground < ActiveRecord::Base
  attr_accessible :name, :description, :image, :price, :user_id, :address_id

  validates :name, presence: true, length: { minimum: 6, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  validates :price, presence: true
  validates :address_id, presence: true
  validates :user_id, presence: true

  has_many :comments, class_name: 'Comment'
  belongs_to :user, foreign_key: :user_id, class_name: 'User'
  belongs_to :address, foreign_key: :address_id, class_name: 'Address'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :user_id, :campground_id, :parent_id

  validates :text, presence: true, length: { minimum: 1, maximum: 1000 }

  belongs_to :user, foreign_key: :user_id, class_name: 'User'
  belongs_to :campground, foreign_key: :campground_id, class_name: 'Campground'
  belongs_to :parent, foreign_key: :parent_id, class_name: 'Comment'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :image, :birthday, :description, :phone, :active, :address_id

  validates :email, presence: true, length: { minimum: 3, maximum: 50 }
  validates :password, presence: true

  has_many :campgrounds, class_name: 'Campground'
  has_many :comments, class_name: 'Comment'
  belongs_to :address, foreign_key: :address_id, class_name: 'Address'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { :locale => I18n.locale }
  end
end

app/controllers/campgrounds_controller.rb
class CampgroundsController < ApplicationController
  def index
    @campgrounds = Campground.all
  end

  def show
    @campground = Campground.find_by_id(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/pages_controller.rb
# Pages Controller
class PagesController < ApplicationController
  def landing
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
  def format_address(add_obj)
    "#{add_obj.street} #{add_obj.city}, #{add_obj.state}, #{add_obj.country}, #{add_obj.zip_code}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active(controller)
    params[:controller] == controller ? 'active' : nil
  end
end

app/helpers/campgrounds_helper.rb
module CampgroundsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/campgrounds/index.html.erb
<%= render "layouts/header" %>

<div class="container">

  <div class="h-100 p-5 m-2 text-white bg-secondary rounded-3 text-center">
    <h1 class="display-4"><%= t('title.welcome_yelpcamp') %></h1>
    <p class="lead"><%= t('title.view_all_our_campgrounds') %></p>
    <%# if(typeof user != 'undefined'){ %>
<!--      <a class="btn btn-primary btn-lg" href="#" data-toggle="modal" data-target="#modal-create-campground">add a new campground</a>-->
      <%# } %>
    </div>

    <div class="row text-center">
      <% @campgrounds.each do |campground| %>
        <div class="card col-lg-3 col-md-6 mb-4 h-100">
          <img class="card-img-top" src="https://media.discordapp.net/attachments/895251767065985036/899700191597309982/inconnu.jpeg?width=1072&height=508" alt="">
          <div class="card-body">
            <h5 class="card-title fs-6"><%= campground.name %></h5>
          </div>
          <div class="card-footer">
            <%= link_to t('button.more_info'), campground, class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>

</div>

app/views/campgrounds/show.html.erb
<%= render "layouts/header" %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <p class="lead"><%= @campground.name %></p>

      <ul class="list-group">
        <li class="list-group-item"><%= @campground.user.email %></li>
        <li class="list-group-item"><%= @campground.user.phone || t('defaults.no_phone') %></li>
        <li class="list-group-item"><%= format_address(@campground.user.address) %></li>
        <%= link_to t('button.return_to_campgrounds'), campgrounds_path, class: 'list-group-item list-group-item-action active' %>
      </ul>
    </div>

    <div class="col-md-9">
      <div class="card" style="width: 100%; padding: 5px;">
        <img class="card-img-top img-fluid" src="https://media.discordapp.net/attachments/895251767065985036/899700191597309982/inconnu.jpeg?width=1072&height=508" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= @campground.name %></h5>
          <p class="card-text"><%= @campground.description %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <%= link_to 'Yelpcamp', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-items" aria-controls="navbar-items" aria-expanded="false" aria-label="<%= t('tooltip.toggle_navigation') %>">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-items">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to t('title.campgrounds'), campgrounds_path, class: "nav-link #{is_active('campgrounds')}" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpcampRails</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 5rem;">

  <%= yield %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/landing.html.erb
<div id="landing-header">
  <h1><%= t('title.welcome_yelpcamp') %></h1>
  <%= link_to t('button.view_all_campgrounds'), campgrounds_path, class: 'btn btn-lg btn-success' %>
</div>

<ul class="slideshow">
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
</ul>